[package]
name = "cargo-wasi"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/cargo-wasi"
readme = "../../README.md"
description = """
TODO description
"""

[workspace]

[dependencies]
cfg-if = "0.1"

[target.'cfg(all(target_arch = "x86_64", target_os = "windows"))'.dependencies]
cargo-wasi-exe-x86_64-pc-windows-msvc = "=1.0.0"

[target.'cfg(all(target_arch = "x86_64", target_os = "macos"))'.dependencies]
cargo-wasi-exe-x86_64-apple-darwin = "=1.0.0"

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
cargo-wasi-exe-x86_64-unknown-linux-musl = "=1.0.0"
