[package]
name = "cargo-wasi"
version = "0.1.2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/cargo-wasi"
readme = "README.md"
description = """
Subcommand for Cargo to easily build code for `wasm32-wasi`
"""

[workspace]
members = [
  'crates/assemble',
  'crates/cargo-wasi-shim',
]
exclude = ['tmp']
