[package]
name = "cargo-wasi-impl"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[workspace]
members = [
  'crates/cargo-wasi',
  'crates/cargo-wasi-exe',
]
