[package]
name = "cargo-wasi"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
readme = "../../README.md"
license = "MIT/Apache-2.0"

## TARGET-SPECIFIC-DEPENDENCIES

[dependencies]
